### PR TITLE
Error facet fix

### LINKED ISSUE #2687: correctness filter not behaving correctly.
- When highlight both it seems to exclude the incorrect labels
- Also the facet is missing the baseline bars
Peek 2021-06-03 14-18

### PR DESCRIPTION
**Pull request by Zac-hills**
closes #2687
Peek 2021-06-03 15-52

### CODE REVIEW

File: api/model/storage/postgres/filter.go [hunk 1]
```diff
@@ -439,16 +439,14 @@ func (s *Storage) buildCorrectnessResultWhere(wheres []string, params []interfac
 		for _, category := range f.Categories {
 			if strings.EqualFold(category, CorrectCategory) {
 				op = "="
-				break
 			} else if strings.EqualFold(category, IncorrectCategory) {
 				op = "!="
-				break
 			}
+			if op == "" {
```
Comment (phorne-uncharted) [inline api/model/storage/postgres/filter.go:445]: Since this check was moved inside the loop, `op := ""` should also be inside the loop.
