### PR TITLE
Timestamp Extrema Crash

### LINKED ISSUE #2268: Date/Time extrema failing to calculate
Bring up the ACLED dataset with the event date set to be a Date/Time results in the following error being generated from the server:

```
[ Feb 10 16:18:23 ] [ WARN ] defaulting extrema values due to error fetching extrema for 'Event_Date': can't scan into dest[0]: cannot assign 1514764800 into *time.Time
no min / max aggregation found
github.com/uncharted-distil/distil/api/model/storage/postgres.(*DateTimeField).parseExtrema
        /home/chris/dev/git_work/distil/api/model/storage/postgres/datetime.go:334
github.com/uncharted-distil/distil/api/model/storage/postgres.(*DateTimeField).fetchExtremaStorage
        /home/chris/dev/git_work/distil/api/model/storage/postgres/datetime.go:554
github.com/uncharted-distil/distil/api/model/storage/postgres.(*Storage).FetchExtrema
        /home/chris/dev/git_work/distil/api/model/storage/postgres/variable.go:83
github.com/uncharted-distil/distil/api/routes.VariablesHandler.func1
        /home/chris/dev/git_work/distil/api/routes/variables.go:67
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2042
goji.io/v3.dispatch.ServeHTTP
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/dispatch.go:17
github.com/uncharted-distil/distil/api/middleware.Gzip.func1
        /home/chris/dev/git_work/distil/api/middleware/gzip.go:61
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2042
github.com/uncharted-distil/distil/api/middleware.Log.func1
        /home/chris/dev/git_work/distil/api/middleware/log_http.go:37
net/http.HandlerFunc.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2042
goji.io/v3.(*Mux).ServeHTTP
        /home/chris/dev/go_workspace/pkg/mod/goji.io/v3@v3.0.0/mux.go:74
net/http.serverHandler.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2843
net/http.(*conn).serve
        /usr/lib/go/src/net/http/server.go:1925
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1374 (api/routes/variables.go:69)
```

### PR DESCRIPTION
**Pull request by phorne-uncharted**
Fixes #2268

Timestamp extremas were failing because the query was converting to integer for this specific route whereas the parsing code had been updated in the past to expect a timestamp (all other extrema queries for timestamps work as expected). In fixing this, some no longer useful (and downright bad) code has been removed.

### CODE REVIEW

File: api/model/storage/postgres/numerical.go [hunk 1]
```diff
@@ -680,7 +680,7 @@ func (f *NumericalField) getNaNFilter() string {
 }
 
 func (f *NumericalField) fetchExtremaStorage() (*api.Extrema, error) {
-	aggQuery := f.Storage.getMinMaxAggsQuery(f.Key, f.Type)
+	aggQuery := f.getMinMaxAggsQuery(f.Key)
```
Comment (Zac-hills) [inline api/model/storage/postgres/numerical.go:683]: Just some clarification about the use of getMinMaxAggsQuery. Above the key was not needed but here the key is needed?
