### PR TITLE
fixed geoplot not loading images. Fixed timestamp facet.

### LINKED ISSUE #2264: Unable to select table rows
When you click on a table row, the row should highlight in pink, and the facets should update their visuals such that the bars containing the selected row values are likewise highlighted in pink.  This is no longer working.

### PR DESCRIPTION
**Pull request by Zac-hills**
closes #2264
image

- After tracking down the source of the issue:
- https://github.com/uncharted-distil/distil/blob/main/api/model/storage/elastic/variable.go#L429
- The d3mIndex variable had a distilRole of Data causing it to be filtered out. The d3mIndex is required for rowSelection. Upon reingesting the baseball ds shown above. The d3mIndex is given the proper distilRole. In order to fix this we just need to do a reingest of all the datasets.
- Fixed map not loading images
- Fixed timestamp not showing rowSelection (there was a key mismatch)

### CODE REVIEW

File: public/components/GeoPlot.vue [hunk 1]
```diff
@@ -602,14 +599,11 @@ export default Vue.extend({
 
     // Return name of column used as grouping column for the table data
     multibandImageGroupColumn(): string {
+      console.log(datasetGetters.getVariables(this.$store));
```
Comment (phorne-uncharted) [inline public/components/GeoPlot.vue]: Probably want to remove this
