### PR TITLE
Split On New Label

### LINKED ISSUE #2185: Panic splitting pre-featurized datasets
On a pre-featurized dataset the following error is produced when creating models:

```
[ Jan 14 17:21:19 ] [ INFO ] checking folders `/home/chris/outputs/locust_medium_d3m-c482871493a0d0a4/train/datasetDoc.json` & `/home/chris/outputs/locust_medium_d3m-c482871493a0d0a4/test/datasetDoc.json` to see if the dataset has been previously split (api/compute/split.go:463)
panic: runtime error: index out of range [-1]

goroutine 25494027 [running]:
github.com/uncharted-distil/distil/api/compute.(*stratifiedSplitter).splitCategories(0xc0217d52c0, 0xffffffffffffffff, 0xc079544018, 0x439c, 0x439c, 0xc0012466b7)
        /home/chris/dev/git_work/distil/api/compute/split.go:254 +0x285
github.com/uncharted-distil/distil/api/compute.(*stratifiedSplitter).split(0xc0217d52c0, 0xc079544000, 0x439d, 0x439d, 0x439d, 0x439d, 0x0, 0x0, 0x0, 0x0, ...)
        /home/chris/dev/git_work/distil/api/compute/split.go:279 +0x315
github.com/uncharted-distil/distil/api/compute.SplitDataset(0xc004874190, 0x4a, 0x11f8b00, 0xc0217d52c0, 0x4a, 0xc000985401, 0xc0012466b7, 0x7, 0x3fe322d0e5604189, 0x0)
        /home/chris/dev/git_work/distil/api/compute/split.go:331 +0x475
github.com/uncharted-distil/distil/api/compute.(*SolutionRequest).PersistAndDispatch(0xc0010dbe60, 0xc0003101e0, 0x1219580, 0xc000eaa330, 0x1217c60, 0xc000eaa2d0, 0x1219ba0, 0xc000eaa2a0, 0x3fe999999999999a, 0x10001)
        /home/chris/dev/git_work/distil/api/compute/solution_request.go:758 +0xa0f
github.com/uncharted-distil/distil/api/ws.handleCreateSolutions(0xc000b74040, 0xc0003101e0, 0xc0003f8e70, 0xc0004189c0, 0xc0004189e0, 0xc00069af50)
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:189 +0x56b
github.com/uncharted-distil/distil/api/ws.handleMessage(0xc000b74040, 0xc0003101e0, 0xc0003f8e70, 0xc0004189c0, 0xc0004189e0, 0xc0003f8ea0, 0xc00069af50)
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:101 +0x285
created by github.com/uncharted-distil/distil/api/ws.handleSolutionMessage.func1
        /home/chris/dev/git_work/distil/api/ws/pipeline.go:92 +0x211
exit status 2
```

### PR DESCRIPTION
**Pull request by phorne-uncharted**
Fixes #2185 

Prefeaturized datasets were not cloning and updating the prefeaturized data when saving the new labels. Added the notion of parent dataset, and use it to identify the new fields to add to the prefeaturized data.

There were also a bunch of small problems made evident during this fix:
- result parsing errors were not propagated properly
- results from TA2 use the header name for the target name and not the display name
- parquet dataset reading was still using csv to read the metadata and augmenting fields assuming a csv data file
- saving a dataset was dropping unlabeled rows from the data table (correct) but labeled rows from the data on disk (incorrect)

### CODE REVIEW

File: api/model/storage/postgres/result.go [hunk 1]
```diff
@@ -293,7 +293,7 @@ func (s *Storage) PersistResult(dataset string, storageName string, resultURI st
 	}
 
 	// Translate from display name to storage name.
```
Comment (Zac-hills) [inline api/model/storage/postgres/result.go:295]: // Translate from header name to storage name.

**Review by Zac-hills — COMMENTED** [review]
looks good, there was a comment from the previous code that might need a slight change.
