### PR TITLE
Render primitives

### LINKED ISSUE #2323: Point maps not working
When a lat/lon type was created for `ACLED_clean` and added to the feature set, the map view was unable to load.  The following exception is thrown by the client:

```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'coordinates' of undefined
    at eval (GeoPlot.vue:1061)
    at Array.forEach (<anonymous>)
    at VueComponent.areaToPoints (GeoPlot.vue:1060)
    at Object.quads (GeoPlot.vue:720)
    at VueComponent.createLumoMap (GeoPlot.vue:800)
    at VueComponent.mounted (GeoPlot.vue:780)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854)
    at callHook (vue.runtime.esm.js:4219)
    at Object.insert (vue.runtime.esm.js:3139)
    at invokeInsertHook (vue.runtime.esm.js:6346)
```

Note that the above exception is just a symptom of a larger problem - it looks like the geoplot is expecting its data to be quads, whereas it use to support point or quad data.  There also seems to be a large amount of dead code present in the file that should be cleaned up.

### PR DESCRIPTION
**Pull request by Zac-hills**
Fix for geo coordinates not working.
closes #2323

### CODE REVIEW

File: public/components/GeoPlot.vue [hunk 1]
```diff
@@ -838,16 +773,18 @@ export default Vue.extend({
     getInterestBounds(area: Area): LatLngBoundsLiteral {
       const xDistance = (this.drillDownState.numCols - 1) / 2;
       const yDistance = (this.drillDownState.numRows - 1) / 2;
-      const tileWidth = area.coordinates[1][1] - area.coordinates[0][1];
-      const tileHeight = area.coordinates[1][0] - area.coordinates[0][0];
+      const tileWidth =
+        area.info.coordinates[1][1] - area.info.coordinates[0][1];
```
Comment (YohannParis) [inline public/components/GeoPlot.vue:777]: I see that you need the tile width and height here and in the _drilldown_ component. 
Maybe you could add it to the class `CoordinateInfo`, so the next reader doesn't need to check if `coordinates[0]` is _Lat_ or _Long_.
You could also add `lat` and `long` as properties for a more straightforward use; thus, only `util/rendering/coordinates.ts` will manage which one is which.

To resume, something like this:
```js
export abstract class CoordinateInfo {
  coordinates: LatLngBoundsLiteral;
  lat: number,
  long: number,
  height: number,
  width: number,
  ...
}
```

**Review by YohannParis — APPROVED** [review]
I love the tidying up of the `GeoPlot` component by creating a new `util`.

Everything works as expected, and displays where it should be.
