### PR TITLE
Fix ImageOreview

### LINKED ISSUE #2365: Media Files and ImagePreview
image

Shown in the above picture the facets are displaying the correct image but the data view is not.
Might be an issue where the ResultDataSlot is not passing in the correct flag to the ImagePreview

### PR DESCRIPTION
**Pull request by YohannParis**
fix #2365 

The `unique-trail` prop was wrongly used to fetch images of type `IMAGE_TYPE`.

The Image file creation is so overblown, why do we save HTMLImageElement when we only need them for their URLs?

### CODE REVIEW

File: public/components/ImagePreview.vue [hunk 1]
```diff
@@ -205,56 +134,76 @@ export default Vue.extend({
...
     imageAttentionIsLoaded(): boolean {
       return (
         !!this.solutionId &&
         !!this.row &&
         !!this.files[this.solutionId + this.row.d3mIndex]
       );
     },
+
     image(): HTMLImageElement {
+      if (this.type === IMAGE_TYPE) {
```
Comment (YohannParis) [inline public/components/ImagePreview.vue:179]: Second line that solves the issue.

**Review by Zac-hills — APPROVED** [review]
