### PR TITLE
Multiple highlight fixes

### LINKED ISSUE #2353: Result Summary highlight issue
https://github.com/uncharted-distil/distil/blob/main/public/util/highlights.ts#L94

createFiltersFromHighlights fails when a rank summary is part of the highlight causing an undefined being passed down into the backend. When an undefined is found in the backend all the highlights are disregarded.

### PR DESCRIPTION
**Pull request by Zac-hills**
- Changed result summary backend to support multiple highlights of each
- Added support on the client for result summary highlights
- Added result and prediction summary support for lexbar
NOTE:
- Result and prediction screen do not work as intended with multiple highlights due to an AND in the backend (future work will rectify this issue)
-closes #2353

### CODE REVIEW

File: api/model/storage/postgres/result.go [hunk 1]
```diff
@@ -789,63 +789,73 @@ func (s *Storage) FetchResults(dataset string, storageName string, resultURI str
...
-		if filters.predictedFilter.Mode == model.IncludeFilter {
-			wheres, params, err = addIncludePredictedFilterToWhere(wheres, params, filters.predictedFilter, variable)
-			if err != nil {
-				return nil, errors.Wrap(err, "Could not add result to where clause")
-			}
-		} else {
-			wheres, params, err = addExcludePredictedFilterToWhere(wheres, params, filters.predictedFilter, variable)
-			if err != nil {
-				return nil, errors.Wrap(err, "Could not add result to where clause")
+	if len(filters.predictedFilters) > 0 {
```
Comment (phorne-uncharted) [inline api/model/storage/postgres/result.go:792]: you dont need a check if you just iterate over it

File: api/model/storage/postgres/result.go [hunk 2]
```diff
@@ -789,63 +789,73 @@ func (s *Storage) FetchResults(dataset string, storageName string, resultURI str
...
-		if filters.correctnessFilter.Mode == model.IncludeFilter {
-			wheres, params, err = addIncludeCorrectnessFilterToWhere(wheres, params, filters.correctnessFilter, variable)
-			if err != nil {
-				return nil, errors.Wrap(err, "Could not add result to where clause")
-			}
-		} else {
-			wheres, params, err = addExcludeCorrectnessFilterToWhere(wheres, params, filters.correctnessFilter, variable)
-			if err != nil {
-				return nil, errors.Wrap(err, "Could not add result to where clause")
+	if len(filters.correctnessFilters) > 0 {
```
Comment (phorne-uncharted) [inline api/model/storage/postgres/result.go:809]: you dont need the if when you just iterate over it

File: api/model/storage/postgres/timeseries.go [hunk 3]
```diff
@@ -598,10 +598,12 @@ func (f *TimeSeriesField) FetchSummaryData(resultURI string, filterParams *api.F
 	joins := make([]*joinDefinition, 0)
 	wheres := []string{}
 	params := []interface{}{}
-	if filtersSplit.residualFilter != nil {
-		wheres, params, err = f.Storage.buildErrorResultWhere(wheres, params, filtersSplit.residualFilter)
-		if err != nil {
-			return nil, err
+	if len(filtersSplit.residualFilters) > 0 {
```
Comment (phorne-uncharted) [inline api/model/storage/postgres/timeseries.go:601]: iterating over it is sufficient
